#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
  site_name: 'BOOKFLIX <em style="font-size: 80%;">Admin Panel</em>'
  entities:
    Novedades:
        class: App\Entity\Novedad
        list:
          fields: ['titulo', 'descripcion', { property: 'foto', type: 'image', base_path: '%app.path.novedades_images%' }]
        form:
          fields: ['titulo', 'descripcion', { property: 'fotoFile', type: 'vich_image', upload_dir: '%app.path.novedades_images%', upload_filename: '[year]/[month]/[day]/[slug]-[contenthash].[extension]' }]
  design:
      menu:
          - { label: 'Novedad' }
          - { entity: 'Novedades', icon: 'newspaper' }